name: BukkitAssist
version: 1.0
main: com.projectteam.bukkitassist.Main
author: emericask8ur
description: Bukkit/Minecraft API.
commands:
  BukkitAssist:
   description: Version
   usage: /BukkitAssist